# Build pages on push, pull request or merge
on:
	push:
		branches: [pages-dev]
	pull_request:
		branches: [pages-dev]

jobs:
	build:
		steps:
			- uses: actions/checkout@v2
			- uses: borales/actions-yarn@v2.3.0
        	  with:
			  	cmd: install
			- uses: borales/actions-yarn@v2.3.0
        	  with:
			  	cmd: build
