on:
  push:
    branches: [ pages-dev ]
  pull_request:
    branches: [ pages-dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: build:github
    - uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: pages
        FOLDER: public
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
